### ISSUE TITLE
How we can make it as proper production app with all possibilities with call kit and Push Messages

### ISSUE THREAD

**Issue by farhanmirza27** [stasel/WebRTC-iOS#11]

**Comment by farhanmirza27** [comment]
If you can provide that and complete guide about what you have currently developed that will be great with a guide

**Comment by stasel** [comment]
Hi @farhanmirza27 
Unfortunately writing such guide will take a lot of effort and time and this is not the purpose of this demo project. This demo project's goal to make you familiar with WebRTC technology.

But here is a short (but not complete) checklist that you need to investigate in order to have a production level guide:

- Deploy your own STUN and TURN servers (Info available online)
- Have a proper signaling server so one client can send a call request to other client. You can use you favorite language and method here.
- Setup your app to use push notifications (Info available at developer.apple.com)
- Add CallKit to your app (watch WWDC video about CallKit and read my notes about connecting CallKit with WebRTC)

For a commercial app, I would also strongly advice to consult with VoIP expert as well.

**Comment by saroar** [comment]
@farhanmirza27 i did already if need help let me know
