### ISSUE TITLE
Dependencies could not be resolved

### ISSUE THREAD

**Issue by mathist** [stasel/WebRTC-iOS#110]
When building the project to an iPhone or Simulator, I get this error:

Dependencies could not be resolved because no versions of 'swift-nio-zlib-support' match the requirement 1.0.0..<2.0.0 and root depends on 'starscream' 3.1.1..<4.0.0.
'starscream' 3.1.1..<4.0.0 practically depends on 'swift-nio-zlib-support' 1.0.0..<2.0.0 because 'starscream' 3.1.1 depends on 'swift-nio-zlib-support' 1.0.0..<2.0.0 and no versions of 'starscream' match the requirement 3.1.2..<4.0.0.

**Comment by stasel** [comment]
That's strange. Do you need to support iOS 12? If not, you can remove `starscream` from the project and use the native web socket support

**Comment by raymondwelch33** [comment]
Whilst inspecting I discovered package dependency on `swift-nio-zlib-support` (https://github.com/apple/swift-nio-zlib-support) - I am creating a separate issue for this matter because I do not understand why the demo app depends on the zlib support package... which is deprecated... and in the package's repository it states instructions on how to gain support from the new, proper package. See - [(https://github.com/apple/swift-nio-zlib-support/commit/cd3ad8e66fb389b80fd84b8b07561452d653e6f7)]

**Comment by raymondwelch33** [comment]
Whilst inspecting this fine repository, I discovered a `Swift Package Manager` dependency on the package, `swift-nio-zlib-support` - mentioned above, and linked just below. 

**Repo:** (https://github.com/apple/swift-nio-zlib-support). 

I am creating a separate issue for this matter because I do **NOT** understand why the demo app even has this dependency in the first place. It is seems the package by Apple is deprecated and suggested to **NOT** be used to gain the functionality it previously enabled. Moreover, in the package's repository it has instructions on how to gain the same support / functionality from the new package linked just below: 

**New Repo:** https://github.com/apple/swift-nio-extras

Please see the final commit, pushed around 15 months ago - https://github.com/apple/swift-nio-zlib-support/commit/cd3ad8e66fb389b80fd84b8b07561452d653e6f7

**Comment by stasel** [comment]
Thanks again @raymondwelch33 for the detailed investigation.
As mentioned in #121 , updating `starscream` lib to the latest version got rid of this dependency

**Comment by raymondwelch33** [comment]
No problem. You're more knowledgeable than I am regarding iOS 12 - iOS 13 support. 

Is it okay that we removed that lib if the main target or package is set to iOS 12.0? 

Just a final, double check - if you will.

**Comment by stasel** [comment]
Yeah, you can safely remove Starscream as it only being used for iOS 12.
You can of course decide to use it anyways of course, it doesn't matter which web socket library is used in this demo project.

**Comment by raymondwelch33** [comment]
I am asking - let's say we want to have iOS 12 support and thus, Starscream. Do we still need Apple's zlib support library?

**Comment by raymondwelch33** [comment]
I thought you can just do `import zlib` - with latest Xcode and it will work fine like that.
