### ISSUE TITLE
kurento implementation

### ISSUE THREAD

**Issue by tombaki** [stasel/WebRTC-iOS#24]
@stasel 
please help to implementation with kurento 
i'v made a greate progress with that's but i don't know how to create array of pc
[https://github.com/chapin666/kurento-group-call-node](url)

**Comment by stasel** [comment]
Hello @tombaki 
I suggest avoiding creating array of peer connecting clients since it doesn't scale at all. Handling multiple open peer connection client means that the device will send it's video streams to multiple users at one which means a very high load on the cpu, network and very high battery consumption.

I suggest investigating on implementing a WebRTC MCU server instead.

Since this is not related with the repo's code, I'm closing this issue.
Feel free to open a new issue if you have any specific problems with the code itself.

Thanks
