### ISSUE TITLE
1 to Many is working?

### ISSUE THREAD

**Issue by saroar** [stasel/WebRTC-iOS#6]
is your app working one to many users 

https://gist.github.com/saroar/20cde456d4952f0f3644c187303bdd7b
https://gist.github.com/saroar/0642f9fa96cf46a022a9043b4e4a68fe

i try this way does not work but then i try one to one its working (for 1 to 1 i have other code )

**Comment by stasel** [comment]
Hi saroar,
Unfortunately, in this demo app, I have implemented only one to one calls. Group calls are out of the scope for this demo.
Group call has several different implementation methods, I suggest watching the  [Intro to WebRTC](https://www.youtube.com/watch?v=p2HzZkd2A40) video where it is briefly explained.

**Comment by tchapi** [comment]
Hi @stasel and thanks for your demo app that is very useful.

Just a quick question : how would you implement sending the stream to another party while maintaining the actual functionality ?
I would like to send the stream to another supplementary WebRTC peer to record it there.

My custom signaling app can of course broadcast the sdp and ice messages to all the needed parties but I guess I need to instantiate two **WebRTCClient** in the app, one for each peer connection.

If you have any hints that would be great.
Thanks again !

**Comment by stasel** [comment]
Hi @tchapi Sorry for the late response.
I'm happy that you (and many other) find this small demo app useful understanding how WebRTC works.

There are two possible solutions of doing this:

1. Connect directly to two WebRTC clients, one is the other peer and one is the recording peer. The disadvantage of this is that the client will have to send two streams to two different peers which consumes double the resources on the device (battery, cpu and traffic).
2. Have a MCU Server to handle the broadcast (and recording). Basically you need to deploy a server which the client connects to (instead of directly to the other peer) and this server broadcasts the video/audio to the other parties (and can of course, record)

I am not very familiar with the implementation of a MCU server but they are mentioning it in the intro to WebRTC video from 2013 [at 23:21](https://youtu.be/p2HzZkd2A40?t=1401).

Good luck!
