### ISSUE TITLE
M1 arm64 issues I guess ?

### ISSUE THREAD

**Issue by lucas-goldner** [stasel/WebRTC-iOS#80]
Hey I just downloaded the demo because I wanted to figure out how I can use your WebRTC implementation, but when I try to build the app I get this tracelog:

It occurs at: Link WebRTC-Demo (arm64)

```
ld: warning: ignoring file /Users/lucasgoldner/Library/Developer/Xcode/DerivedData/WebRTC-Demo-bdqvxahvrhxqczexgpdlclbijqxh/Build/Products/Debug-iphonesimulator/WebRTC.framework/WebRTC, missing required architecture arm64 in file /Users/lucasgoldner/Library/Developer/Xcode/DerivedData/WebRTC-Demo-bdqvxahvrhxqczexgpdlclbijqxh/Build/Products/Debug-iphonesimulator/WebRTC.framework/WebRTC (1 slices)
ld: warning: all bitcode will be dropped because '/Users/lucasgoldner/Library/Developer/Xcode/DerivedData/WebRTC-Demo-bdqvxahvrhxqczexgpdlclbijqxh/Build/Products/Debug-iphonesimulator/Starscream.o' was built without bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. 
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RTCDefaultVideoEncoderFactory", referenced from:
      objc-class-ref in WebRTCClient.o
  "_OBJC_CLASS_$_RTCPeerConnectionFactory", referenced from:
      objc-class-ref in WebRTCClient.o
  "_OBJC_CLASS_$_RTCVideoTrack", referenced from:
      objc-class-ref in WebRTCClient.o
  "_OBJC_CLASS_$_RTCAudioTrack", referenced from:
      objc-class-ref in WebRTCClient.o
  "_OBJC_CLASS_$_RTCRtpTransceiver", referenced from:
      objc-class-ref in WebRTCClient.o
  "_OBJC_CLASS_$_RTCDataBuffer", referenced from:
      objc-class-ref in WebRTCClient.o
  "_OBJC_CLASS_$_RTCConfiguration", referenced from:
      objc-class-ref in WebRTCClient.o
  "_OBJC_CLASS_$_RTCIceCandidate", referenced from:
      objc-class-ref in IceCandidate.o
      objc-class-ref in WebRTCClient.o
  "_OBJC_CLASS_$_RTCIceServer", referenced from:
      objc-class-ref in WebRTCClient.o
  "_RTCInitializeSSL", referenced from:
      closure #1 () -> __C.RTCPeerConnectionFactory in variable initialization expression of static WebRTC_Demo.WebRTCClient.(factory in _08FB3D1CC6B5042F2650C4103C361173) : __C.RTCPeerConnectionFactory in WebRTCClient.o
  "_OBJC_CLASS_$_RTCDataChannelConfiguration", referenced from:
      objc-class-ref in WebRTCClient.o
  "_OBJC_CLASS_$_RTCAudioSession", referenced from:
      objc-class-ref in WebRTCClient.o
  "_OBJC_CLASS_$_RTCCameraVideoCapturer", referenced from:
      objc-class-ref in WebRTCClient.o
  "_kRTCMediaConstraintsOfferToReceiveAudio", referenced from:
      variable initialization expression of WebRTC_Demo.WebRTCClient.(mediaConstrains in _08FB3D1CC6B5042F2650C4103C361173) : [Swift.String : Swift.String] in WebRTCClient.o
      WebRTC_Demo.WebRTCClient.init() -> WebRTC_Demo.WebRTCClient in WebRTCClient.o
      WebRTC_Demo.WebRTCClient.init(iceServers: [Swift.String]) -> WebRTC_Demo.WebRTCClient in WebRTCClient.o
  "_kRTCMediaConstraintsValueTrue", referenced from:
      variable initialization expression of WebRTC_Demo.WebRTCClient.(mediaConstrains in _08FB3D1CC6B5042F2650C4103C361173) : [Swift.String : Swift.String] in WebRTCClient.o
      WebRTC_Demo.WebRTCClient.init() -> WebRTC_Demo.WebRTCClient in WebRTCClient.o
      WebRTC_Demo.WebRTCClient.init(iceServers: [Swift.String]) -> WebRTC_Demo.WebRTCClient in WebRTCClient.o
  "_OBJC_CLASS_$_RTCSessionDescription", referenced from:
      objc-class-ref in SessionDescription.o
  "_kRTCMediaConstraintsOfferToReceiveVideo", referenced from:
      variable initialization expression of WebRTC_Demo.WebRTCClient.(mediaConstrains in _08FB3D1CC6B5042F2650C4103C361173) : [Swift.String : Swift.String] in WebRTCClient.o
      WebRTC_Demo.WebRTCClient.init() -> WebRTC_Demo.WebRTCClient in WebRTCClient.o
      WebRTC_Demo.WebRTCClient.init(iceServers: [Swift.String]) -> WebRTC_Demo.WebRTCClient in WebRTCClient.o
  "_OBJC_CLASS_$_RTCMediaConstraints", referenced from:
      objc-class-ref in WebRTCClient.o
  "_OBJC_CLASS_$_RTCDefaultVideoDecoderFactory", referenced from:
      objc-class-ref in WebRTCClient.o
  "_OBJC_CLASS_$_RTCMTLVideoView", referenced from:
      objc-class-ref in VideoViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by stasel** [comment]
Hey, thanks for reporting the issue. Unfortunately I don't have access to Apple Silicon mac at the moment so I can't test it myself. I would be awesome if you could check those things for me:

- Is the demo project running well on a device?
- Can you maybe link the xcframework manually and try again? Just to make sure it is not Swift Package Manager issue

Also, if anyone else is having the issue, feel free to comment here.

**Comment by lucas-goldner** [comment]
I tried running it with the xcframework but nothing changed... Cannot test it on real device

**Comment by pdxbenjamin** [comment]
> Also, if anyone else is having the issue, feel free to comment here.

Hi Stasel,

The current version of your Project is working fine, Great job. Thank you so much!
![Screen Shot 2021-03-01 at 1 04 26 AM](https://user-images.githubusercontent.com/1851853/109470190-56e61100-7a2c-11eb-8118-18d664fccd12.png)


I am on an M1 Mac mini, iPhone12 and Current version of the iPad all with current iOS and OS X. 

I downloaded the entire project zip, unzipped and opened the .xcworkspace.
Allowed all the Swift Packages to download automagically.

Changed to my Apple Developer ID in both the General, and Build Settings tabs.

Locally launched the node server by ‘node app.js’ then changed the server name in the config.swift file to my local machines IP address from local etc.

I did have to close and relaunch Xcode a few times, to get everything settled.

I did get one xcode notice that I've attached as a screen shot...

Otherwise ... with my ipad and iphone connected directly into the Mac Mini M1 all is working. 

I tested on Wifi and Verizon Wireless.  All working.. after a bit of this and that with xcode.


Great job thank you

**Comment by pdxbenjamin** [comment]
> Also, if anyone else is having the issue, feel free to comment here.
My only one comment is that if you don't follow the "Run instructions" from the README, and tap the buttons out of order... one device will get a black screen, but be broadcasting the image.

**Comment by stasel** [comment]
Thanks @pdxbenjamin for confirming it works on M1 macs. That warning in the screenshot is because I removed support for 32 bit devices in the project settings and it seems that Xcode doesn't like it. I changed it back to normal architectures to avoid this warning message.

@lucas-goldner Are you still experiencing issues with linking or can we close this issue?
